##===- runtime/Makefile ------------------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
PARALLEL_DIRS=giri

include $(LEVEL)/Makefile.common
