##===- giri/test/UnitTests/test4/Makefile ------------------*- Makefile -*-===##

NAME = example
LDFLAGS = -lm
INPUT ?= 10
#CRITERION ?= -criterion-loc=loc.txt
CRITERION ?= -criterion-inst=inst.txt
MAPPING ?= -mapping-function=main

include ../Makefile.common
