##===- giri/test/UnitTests/test4/Makefile ------------------*- Makefile -*-===##

NAME = example
LDFLAGS = -lm
INPUT ?= 10
CRITERION ?= -criterion-loc=criterion-loc.txt
#CRITERION ?= -criterion-inst=criterion-inst.txt
MAPPING ?= -mapping-function=main

include ../../Makefile.common
