##===- giri/test/UnitTests/test13/Makefile -----------------*- Makefile -*-===##

NAME = matrix_multiply
GIRI_DIR = ../../build/
LDFLAGS = -pthread
INPUT ?= 16 true

include ../UnitTests/Makefile.common

clean-all:
	@ rm -f matrix_file_*
