##===- giri/test/UnitTests/test4/Makefile ------------------*- Makefile -*-===##

DEBUGFLAGS ?= -debug
NAME = plower
LDFLAGS = -lpthread
INPUT ?= 4
CRITERION ?= -criterion-loc=criterion-loc.txt
#CRITERION ?= -criterion-inst=criterion-inst.txt
MAPPING ?= -mapping-function=main

include ../../Makefile.common
