##===- giri/test/UnitTests/test4/Makefile ------------------*- Makefile -*-===##

DEBUGFLAGS ?= -debug
NAME = plower
LDFLAGS = -lpthread
INPUT ?= 4
#CRITERION ?= -criterion-loc=loc.txt
CRITERION ?= -criterion-inst=inst.txt
MAPPING ?= -mapping-function=main

include ../Makefile.common
