##===- giri/test/UnitTests/Makefile.common -----------------*- Makefile -*-===##
#

DEBUGFLAGS ?= -debug
CFLAGS ?= -g -O0 -c -emit-llvm
LDFLAGS ?=
VERSION ?= Release+Debug+Asserts
GIRI_DIR ?= ../../../build/
NAME ?= main

CC = clang
GIRI_LIB_DIR = $(GIRI_DIR)/$(VERSION)/lib
GIRI_BIN_DIR = $(GIRI_DIR)/$(VERSION)/bin

.PHONY: all lib slice

all: lib slice

lib:
	$(MAKE) -s -C $(GIRI_DIR)

slice : $(NAME).bc $(NAME).trace
	@ opt -load $(GIRI_LIB_DIR)/libdgutility.so \
		-load $(GIRI_LIB_DIR)/libgiri.so \
		-bbnum -lsnum \
		-dgiri -tf $(NAME).trace -dfs=true -trace-cd=true \
		-remove-bbnum -remove-lsnum \
		-select-origin-as-main -stats $(DEBUGFLAGS) $< -o /dev/null

$(NAME).trace: $(NAME).trace.exe
	- ./$< $(INPUT)

$(NAME).trace.exe : $(NAME).trace.s $(GIRI_DIR)/runtime/Giri/$(VERSION)/Tracing.o
	$(CC) -fno-strict-aliasing $+ -o $@ $(LDFLAGS)

$(NAME).trace.s : $(NAME).trace.bc
	llc -asm-verbose=false -O0 $< -o $@

$(NAME).trace.bc : $(NAME).bc
	@ opt -load $(GIRI_LIB_DIR)/libdgutility.so \
		-load $(GIRI_LIB_DIR)/libgiri.so \
		-bbnum -lsnum \
		-trace-giri -t $(NAME).trace \
		-remove-bbnum -remove-lsnum \
		-stats $(DEBUGFLAGS) $< -o $@

%.opt.bc: %.bc
	opt -mem2reg -mergereturn -instnamer -o $@ $<

%.bc : %.c
	$(CC) $(CFLAGS) $+ -o $@
%.ll : %.bc
	llvm-dis $< -o $@

.PHONY: ptrace rebuild clean

prtrace: $(NAME).trace
	$(GIRI_BIN_DIR)/prtrace $<

rebuild: clean all

clean:
	@ rm -f *.ll *.bc *.o *.s *.slice *.exe *.trace
