##===- giri/tools/Makefile -----------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL = ..

#
# List all of the subdirectories that we will compile.
#
DIRS = PrintTrace Tracer

include $(LEVEL)/Makefile.common
